-- STAGE 1: Add enum values only (must be separate transaction)
ALTER TYPE "PlanTier" ADD VALUE IF NOT EXISTS 'FREE_TRIAL';
ALTER TYPE "PlanTier" ADD VALUE IF NOT EXISTS 'STARTER';
ALTER TYPE "PlanTier" ADD VALUE IF NOT EXISTS 'ENTERPRISE';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ROLE_TRANSITION';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PLAN_UPGRADE';
